name: Python Testing

on:
  push:
    branches:
      - pydarshan-devel
  pull_request:
    branches:
      #- pydarshan-devel
      - "**"

jobs:
  test_pydarshan:
    strategy:
      matrix:
        platform: [ubuntu-latest,
                   macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest mypy pyflakes asv pytest-cov codecov lxml
          # matplotlib is pinned because of
          # gh-479
          python -m pip install 'matplotlib<3.5'
      - if: ${{matrix.platform == 'macos-latest'}}
        name: Install MacOS deps
        run: |
          brew install automake
      - name: Install darshan-util
        run: |
          mkdir darshan_install
          export DARSHAN_INSTALL_PATH=$PWD/darshan_install
          git submodule update --init
          ./prepare.sh
          cd darshan-util
          mkdir build
          cd build
          ../configure --prefix=$DARSHAN_INSTALL_PATH --enable-shared --enable-apxc-mod --enable-apmpi-mod
          make
          make install
      - name: Install pydarshan
        run: |
          cd darshan-util/pydarshan
          python -m pip install .
      # shim for importlib.resources on Python < 3.9
      - if: ${{matrix.python-version < 3.9}}
        name: Install importlib_resources
        run: |
          python -m pip install -U importlib_resources
      # only install the darshan_logs project in some CI
      # entries so we test proper handling of skips
      # in test suite
      - if: ${{matrix.python-version != 3.8}}
        name: Install darshan_logs package
        run: |
          python -m pip install git+https://github.com/darshan-hpc/darshan-logs.git@main
      - name: Test with pytest
        run: |
          export LD_LIBRARY_PATH=$PWD/darshan_install/lib
          # the test suite is sensitive to
          # relative dir for test file paths
          cd darshan-util/pydarshan
          site_packages=$(pip show darshan | grep Location | cut -d ' ' -f 2)
          pytest --import-mode=importlib --cov-report xml --cov=$site_packages/darshan --cov=tests
      # Python 3.6 doesn't have access to some
      # dependencies needed for our type hints
      - if: ${{matrix.python-version > 3.6}}
        name: mypy check
        run: |
          export LD_LIBRARY_PATH=$PWD/darshan_install/lib
          cd darshan-util/pydarshan
          mypy darshan
          mypy tests
      - name: pyflakes check
        run: |
          cd darshan-util/pydarshan
          pyflakes darshan/backend | (grep -E -i 'assigned to but never used' || exit 0 && exit 123)
      - name: asv check
        run: |
          export LD_LIBRARY_PATH=$PWD/darshan_install/lib
          cd darshan-util/pydarshan/benchmarks
          python -m asv check -E existing
      - name: codecov check
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: False
