name: Runtime Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_runtime:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y hdf5-tools libhdf5-openmpi-dev openmpi-bin
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest pytest-mpi h5py mpi4py
          # the organization of HDF5 files from apt isn't
          # ideal for usage with darshan, but we can cheat
          # a little
          cp /usr/include/hdf5/openmpi/*.h /usr/include
      - name: Install darshan-runtime
        run: |
          mkdir darshan_install
          export DARSHAN_INSTALL_PATH=$PWD/darshan_install
          git submodule update --init
          ./prepare.sh
          cd darshan-runtime
          mkdir build
          cd build
          CC=mpicc ../configure --prefix=$DARSHAN_INSTALL_PATH --with-log-path-by-env=DARSHAN_LOGPATH --with-jobid-env=SLURM_JOBID --enable-hdf5-mod
          make
          make install
      - name: Test with pytest
        run: |
          mpirun --allow-run-as-root -n 1 python -m pytest --with-mpi darshan-test/python_runtime_tests.py
